export const mockSurveyItems = [
  {
    title: "Automobiles",
    thumb: "Automobiles",
    completes: 0,
    duration: 2,
    qualifications: 3,
    coins: 30000,
  },
  {
    title: "Lifestyle",
    thumb: "Lifestyle",
    completes: 8,
    duration: 2,
    qualifications: 3,
    coins: 30000,
  },
  {
    title: "Food",
    thumb: "Food",
    completes: 8,
    duration: 2,
    qualifications: 3,
    coins: 30000,
  },
  {
    title: "Automobiles",
    thumb: "Automobiles",
    completes: 8,
    duration: 2,
    qualifications: 3,
    coins: 30000,
  },
  {
    title: "Technology",
    thumb: "Technology",
    completes: 0,
    duration: 2,
    qualifications: 3,
    coins: 30000,
  },
  {
    title: "Food",
    thumb: "Food",
    completes: 0,
    duration: 2,
    qualifications: 3,
    coins: 30000,
  },
  {
    title: "Lifestyle",
    thumb: "Lifestyle",
    completes: 0,
    duration: 2,
    qualifications: 3,
    coins: 30000,
  },
  {
    title: "Technology",
    thumb: "Technology",
    completes: 8,
    duration: 2,
    qualifications: 3,
    coins: 30000,
  },
];
